version: "3.8"
services:
  app:
    image: npm-next-app
    build: .
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./:/home/node/app
      - next-modules:/home/node/app/node_modules
volumes: 
  next-modules:
